export default function Head() {
    return (
      <>
        <title>LE ROI DES FRIANDISES</title>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }
  